fix this error
Error: React has detected a change in the order of Hooks called by CourseManagementPage. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://react.dev/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useState                   useState
3. useState                   useState
4. useState                   useState
5. useState                   useState
6. useState                   useState
7. useState                   useState
8. useState                   useState
9. useState                   useState
10. useState                  useState
11. useState                  useState
12. useState                  useState
13. useState                  useState
14. useState                  useState
15. useState                  useState
16. useState                  useState
17. useState                  useState
18. useState                  useState
19. useState                  useState
20. useState                  useState
21. useState                  useState
22. useState                  useState
23. useState                  useState
24. useState                  useState
25. useState                  useState
26. useState                  useState
27. useState                  useState
28. useState                  useState
29. useState                  useState
30. useState                  useState
31. useState                  useState
32. useState                  useState
33. useState                  useState
34. useState                  useState
35. useState                  useState
36. useState                  useState
37. useState                  useState
38. useState                  useState
39. useState                  useState
40. useState                  useState
41. useState                  useState
42. useState                  useState
43. useEffect                 useEffect
44. useEffect                 useEffect
45. useEffect                 useEffect
46. useEffect                 useEffect
47. useMemo                   useMemo
48. useMemo                   useMemo
49. useEffect                 useEffect
50. undefined                 useMemo
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at createUnhandledError (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at updateHookTypesDev (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:5438:25)
    at Object.useMemo (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:15194:13)
    at exports.useMemo (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1672:36)
    at CourseManagementPage (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/src_024712aa._.js:1379:204)
    at ClientPageRoot (https://6000-idx-studio-1746514218935.cluster-ys234awlzbhwoxmkkse6qo3fz6.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)

and then implement rest of the pending features as per priority so that we do not have to reiterate on them